name = "Entry Point Dailies"
description = "We make videos."
keywords = "one, two, three"
image = "sparrow_helicopter.jpg"
theme = "dark"
primary_color = "#0ca0fcff"
text_align = "center"
gtag_id = "G-XLJ81DCZFV"
base_url = "https://entrypointdailies.github.io/connect"


[[sections]]
title = "Connect with us"
description = "We're found on these websites"
direction = "row"
item_style = "filled"
icon_size = "30px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/youtube/ffffff"
title = "YouTube"
url = "https://youtube.com/@entrypointdailies"
[[sections.items]]
icon = "https://cdn.simpleicons.org/discord/ffffff"
title = "Discord"
url = "https://discord.com/invite/HrQ6vxvuA5"
[[sections.items]]
icon = "https://cdn.simpleicons.org/github/ffffff"
title = "GitHub"
url = "https://github.com/entrypointdailies"
[[sections.items]]
title = "Message"
icon = "https://cdn.simpleicons.org/gmail/ffffff"
url = "mailto:fervent.labrador416@passinbox.com"
